"""add_custom_behavior_to_session_state

Revision ID: f4df84b2733c
Revises: 003
Create Date: 2025-11-23 20:45:29.146211

"""
from alembic import op
import sqlalchemy as sa


revision = 'f4df84b2733c'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_traces', 'trace_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('request_traces', 'query',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('request_traces', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('request_traces', 'total_time_ms',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('request_traces', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('request_traces', 'steps',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_traces_created_at', table_name='request_traces')
    op.drop_index('idx_traces_trace_id', table_name='request_traces')
    op.drop_constraint('request_traces_trace_id_key', 'request_traces', type_='unique')
    op.drop_column('request_traces', 'id')
    op.add_column('session_state', sa.Column('custom_behavior', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_state', 'custom_behavior')
    op.add_column('request_traces', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('request_traces_trace_id_key', 'request_traces', ['trace_id'])
    op.create_index('idx_traces_trace_id', 'request_traces', ['trace_id'], unique=False)
    op.create_index('idx_traces_created_at', 'request_traces', ['created_at'], unique=False)
    op.alter_column('request_traces', 'steps',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('request_traces', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('request_traces', 'total_time_ms',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('request_traces', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('request_traces', 'query',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('request_traces', 'trace_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
